name: node22
services:
  node0:
    image: node
    size: mili
    active: true
    git:
      url: https://github.com/kolserdav/conhos-test-git.git
      branch: master
      untracked: checkout
    version: latest
    pwd: ./hello-world
    ports:
      - port: 3000
        type: http
    command: npm i && npm run start
    environment:
      - PORT=3000
  node1:
    image: node
    size: mili
    active: true
    git:
      url: https://github.com/kolserdav/conhos-test-git.git
      branch: master
      untracked: checkout
    version: latest
    pwd: ./hello-world
    ports:
      - port: 3000
        type: http
    command: npm i && npm run start
    environment:
      - PORT=3000
  node12:
    image: node
    size: mili
    active: true
    git:
      url: https://github.com/kolserdav/conhos-test-git.git
      branch: master
      untracked: checkout
    version: latest
    pwd: ./hello-world
    ports:
      - port: 3000
        type: http
    command: npm i && npm run start
    environment:
      - PORT=3000
